import type { DashboardLayout, DashboardWidget } from '@repo/shared-types'

const DEFAULT_WIDGETS: DashboardWidget[] = [
  {
    id: 'w1',
    type: 'kpi_active_deals',
    title: 'Active Deals',
    size: '1x1',
    position: 0,
    visible: true,
    config: {},
  },
  {
    id: 'w2',
    type: 'kpi_won_deals',
    title: 'Won This Month',
    size: '1x1',
    position: 1,
    visible: true,
    config: {},
  },
  {
    id: 'w3',
    type: 'kpi_new_contacts',
    title: 'New Contacts',
    size: '1x1',
    position: 2,
    visible: true,
    config: {},
  },
  {
    id: 'w4',
    type: 'kpi_pending_activities',
    title: 'Pending Activities',
    size: '1x1',
    position: 3,
    visible: true,
    config: {},
  },
  {
    id: 'w5',
    type: 'kpi_receivable',
    title: 'Receivable',
    size: '1x1',
    position: 4,
    visible: true,
    config: {},
  },
  {
    id: 'w6',
    type: 'kpi_overdue',
    title: 'Overdue',
    size: '1x1',
    position: 5,
    visible: true,
    config: {},
  },
  {
    id: 'w7',
    type: 'pipeline_summary',
    title: 'Pipeline',
    size: '2x2',
    position: 6,
    visible: true,
    config: {},
  },
  {
    id: 'w8',
    type: 'today_activities',
    title: 'Today',
    size: '2x1',
    position: 7,
    visible: true,
    config: {},
  },
  {
    id: 'w9',
    type: 'revenue_by_month',
    title: 'Revenue Trend',
    size: '2x1',
    position: 8,
    visible: true,
    config: {},
  },
  {
    id: 'w10',
    type: 'top_sales_reps',
    title: 'Top Reps',
    size: '1x1',
    position: 9,
    visible: true,
    config: {},
  },
  {
    id: 'w11',
    type: 'overdue_invoices',
    title: 'Overdue Invoices',
    size: '2x1',
    position: 10,
    visible: false,
    config: {},
  },
  {
    id: 'w12',
    type: 'deal_forecast',
    title: 'Forecast',
    size: '2x1',
    position: 11,
    visible: false,
    config: {},
  },
  {
    id: 'w13',
    type: 'recent_deals',
    title: 'Recent Deals',
    size: '2x1',
    position: 12,
    visible: false,
    config: {},
  },
  {
    id: 'w14',
    type: 'recent_contacts',
    title: 'Recent Contacts',
    size: '2x1',
    position: 13,
    visible: false,
    config: {},
  },
  {
    id: 'w15',
    type: 'low_stock_alert',
    title: 'Low Stock',
    size: '1x1',
    position: 14,
    visible: false,
    config: {},
  },
]

export const DEFAULT_LAYOUT: DashboardLayout = {
  widgets: DEFAULT_WIDGETS,
  columns: 3,
  refreshIntervalSeconds: 300,
}
