// Generated by scripts/gen-brand-palette.mjs from apps/web/src/styles/globals.css.
// Edit the --brand-* custom properties there, not this file.

export const NEXO_BRAND_PALETTE = {
  primary: '#A5E96F',
  primaryForeground: '#0E0F0C',
  secondary: '#F1F3EF',
  accent: '#E4F7D6',
  sidebar: '#F7F8F5',
  sidebarForeground: '#0E0F0C',
} as const
