export { ContactRecordDrawer } from './ui/containers/ContactRecordDrawer'
export type { ContactRecordSource } from './ui/containers/ContactRecordDrawer'
export { ContactRecordHeader } from './ui/ContactRecordHeader'
export { ContactRecordSections } from './ui/ContactRecordSections'
export { ContactDetailsForm } from './ui/ContactDetailsForm'
export { ActivityList } from './ui/ActivityList'
export { ActivityTimeline } from './ui/ActivityTimeline'
export { ContactOwnerPicker } from './ui/containers/ContactOwnerPicker'
export { useContactRecord, type ContactRecord } from './model/useContactRecord'
export { groupContactActivities, type ActivityGroups } from './lib/activity-groups'
