import type { ContactColumnDef } from '@repo/shared-types'

export const CONTACT_COLUMN_CATALOG: readonly ContactColumnDef[] = [
  {
    key: 'name',
    labelKey: 'contacts.columns.name',
    hintKey: 'contacts.columnHints.name',
    sortField: 'firstName',
    defaultVisible: true,
    defaultWidth: 240,
    minWidth: 180,
  },
  {
    key: 'status',
    labelKey: 'contacts.columns.status',
    hintKey: 'contacts.columnHints.status',
    sortField: 'status',
    defaultVisible: true,
    defaultWidth: 150,
    minWidth: 130,
  },
  {
    key: 'email',
    labelKey: 'contacts.columns.email',
    hintKey: 'contacts.columnHints.email',
    sortField: 'email',
    defaultVisible: true,
    defaultWidth: 210,
    minWidth: 160,
  },
  {
    key: 'phone',
    labelKey: 'contacts.columns.phone',
    hintKey: 'contacts.columnHints.phone',
    sortField: null,
    defaultVisible: true,
    defaultWidth: 150,
    minWidth: 120,
  },
  {
    key: 'whatsapp',
    labelKey: 'contacts.columns.whatsapp',
    hintKey: 'contacts.columnHints.whatsapp',
    sortField: null,
    defaultVisible: false,
    defaultWidth: 150,
    minWidth: 120,
  },
  {
    key: 'documentNumber',
    labelKey: 'contacts.columns.documentNumber',
    hintKey: 'contacts.columnHints.documentNumber',
    sortField: null,
    defaultVisible: false,
    defaultWidth: 150,
    minWidth: 120,
  },
  {
    key: 'jobTitle',
    labelKey: 'contacts.columns.jobTitle',
    hintKey: 'contacts.columnHints.jobTitle',
    sortField: null,
    defaultVisible: false,
    defaultWidth: 150,
    minWidth: 120,
  },
  {
    key: 'lifecycleStage',
    labelKey: 'contacts.columns.lifecycleStage',
    hintKey: 'contacts.columnHints.lifecycleStage',
    sortField: null,
    defaultVisible: false,
    defaultWidth: 130,
    minWidth: 110,
  },
  {
    key: 'source',
    labelKey: 'contacts.columns.source',
    hintKey: 'contacts.columnHints.source',
    sortField: null,
    defaultVisible: false,
    defaultWidth: 130,
    minWidth: 100,
  },
  {
    key: 'type',
    labelKey: 'contacts.columns.type',
    hintKey: 'contacts.columnHints.type',
    sortField: null,
    defaultVisible: false,
    defaultWidth: 120,
    minWidth: 100,
  },
  {
    key: 'tags',
    labelKey: 'contacts.columns.tags',
    hintKey: 'contacts.columnHints.tags',
    sortField: null,
    defaultVisible: true,
    defaultWidth: 150,
    minWidth: 120,
  },
  {
    key: 'city',
    labelKey: 'contacts.columns.city',
    hintKey: 'contacts.columnHints.city',
    sortField: 'city',
    defaultVisible: true,
    defaultWidth: 130,
    minWidth: 100,
  },
  {
    key: 'leadScore',
    labelKey: 'contacts.columns.leadScore',
    hintKey: 'contacts.columnHints.leadScore',
    sortField: 'leadScore',
    defaultVisible: false,
    defaultWidth: 110,
    minWidth: 90,
  },
  {
    key: 'lastContactedAt',
    labelKey: 'contacts.columns.lastContactedAt',
    hintKey: 'contacts.columnHints.lastContactedAt',
    sortField: 'lastContactedAt',
    defaultVisible: true,
    defaultWidth: 150,
    minWidth: 120,
  },
  {
    key: 'notes',
    labelKey: 'contacts.columns.notes',
    hintKey: 'contacts.columnHints.notes',
    sortField: null,
    defaultVisible: false,
    defaultWidth: 120,
    minWidth: 100,
  },
  {
    key: 'createdAt',
    labelKey: 'contacts.columns.createdAt',
    hintKey: 'contacts.columnHints.createdAt',
    sortField: 'createdAt',
    defaultVisible: true,
    defaultWidth: 140,
    minWidth: 110,
  },
]
