import type { ContactColumnDef } from '@repo/shared-types'

export const CONTACT_COLUMN_CATALOG: readonly ContactColumnDef[] = [
  {
    key: 'name',
    labelKey: 'contacts.columns.name',
    type: 'name',
    sortable: true,
    editable: false,
    defaultVisible: true,
    defaultWidth: 250,
    minWidth: 180,
  },
  {
    key: 'status',
    labelKey: 'contacts.columns.status',
    type: 'badge',
    sortable: true,
    editable: true,
    defaultVisible: true,
    defaultWidth: 140,
    minWidth: 110,
  },
  {
    key: 'phone',
    labelKey: 'contacts.columns.phone',
    type: 'text',
    sortable: false,
    editable: false,
    defaultVisible: true,
    defaultWidth: 150,
    minWidth: 120,
  },
  {
    key: 'email',
    labelKey: 'contacts.columns.email',
    type: 'text',
    sortable: true,
    editable: false,
    defaultVisible: false,
    defaultWidth: 220,
    minWidth: 160,
  },
  {
    key: 'city',
    labelKey: 'contacts.columns.city',
    type: 'text',
    sortable: true,
    editable: false,
    defaultVisible: true,
    defaultWidth: 120,
    minWidth: 100,
  },
  {
    key: 'lifecycleStage',
    labelKey: 'contacts.columns.lifecycle',
    type: 'badge',
    sortable: false,
    editable: true,
    defaultVisible: false,
    defaultWidth: 140,
    minWidth: 110,
  },
  {
    key: 'source',
    labelKey: 'contacts.columns.source',
    type: 'badge',
    sortable: false,
    editable: false,
    defaultVisible: false,
    defaultWidth: 130,
    minWidth: 100,
  },
  {
    key: 'tags',
    labelKey: 'contacts.columns.tags',
    type: 'tags',
    sortable: false,
    editable: false,
    defaultVisible: false,
    defaultWidth: 180,
    minWidth: 120,
  },
  {
    key: 'leadScore',
    labelKey: 'contacts.columns.leadScore',
    type: 'number',
    sortable: true,
    editable: false,
    defaultVisible: false,
    defaultWidth: 100,
    minWidth: 80,
  },
  {
    key: 'assignedTo',
    labelKey: 'contacts.columns.owner',
    type: 'user',
    sortable: false,
    editable: true,
    defaultVisible: false,
    defaultWidth: 160,
    minWidth: 120,
  },
  {
    key: 'lastContactedAt',
    labelKey: 'contacts.columns.lastActivity',
    type: 'date',
    sortable: true,
    editable: false,
    defaultVisible: false,
    defaultWidth: 130,
    minWidth: 100,
  },
  {
    key: 'createdAt',
    labelKey: 'contacts.columns.created',
    type: 'date',
    sortable: true,
    editable: false,
    defaultVisible: true,
    defaultWidth: 110,
    minWidth: 90,
  },
]
