export { useReducedTransition } from './useReducedTransition'
export {
  DURATION,
  EASE_SMOOTH,
  collapseHorizontal,
  expandCollapse,
  fade,
  fadeSlideUp,
  slideRight,
  slideLeft,
  scaleUp,
  staggerContainer,
  staggerChild,
  smoothSpring,
  smoothEase,
  quickEase,
  indicatorSpring,
  gooeyPopover,
  dockRevealSpring,
  dockSlideSpring,
  gooeySpring,
  snappySpring,
  subtlePopover,
  subtleTween,
  instant,
} from './variants'
